schema_version = "1.0.0"

id = "mw_cs2_window_distributor"
version = "2.7.3"
name = "MW CS2 Window Distributor"
tagline = "Distribute window UV islands across the CS2 window atlas"
maintainer = "MacWelshman"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    ".*",
    "/*.zip",
    "dist/",
]
